// Mock data for development and testing
export const mockData = {
  trucks: [
    {
      id: 'truck-1',
      vin: '1HGBH41JXMN109186',
      licensePlate: 'FLT-001',
      make: 'Freightliner',
      model: 'Cascadia',
      year: 2019,
      mileage: 345000,
      nickname: 'Big Blue',
      status: 'In Service' as const,
      createdAt: new Date('2023-01-15'),
      updatedAt: new Date('2024-08-01'),
    },
    {
      id: 'truck-2',
      vin: '1FUJGLDR53LM76543',
      licensePlate: 'FLT-002',
      make: 'Peterbilt',
      model: '579',
      year: 2020,
      mileage: 298000,
      nickname: 'Red Thunder',
      status: 'Out for Repair' as const,
      createdAt: new Date('2023-03-20'),
      updatedAt: new Date('2024-07-28'),
    },
    {
      id: 'truck-3',
      vin: '3AKJGLDR54LS87654',
      licensePlate: 'FLT-003',
      make: 'Kenworth',
      model: 'T680',
      year: 2021,
      mileage: 156000,
      nickname: 'Silver Bullet',
      status: 'In Service' as const,
      createdAt: new Date('2023-06-10'),
      updatedAt: new Date('2024-08-02'),
    },
    {
      id: 'truck-4',
      vin: '1XKAD49X0LJ123456',
      licensePlate: 'FLT-004',
      make: 'Mack',
      model: 'Anthem',
      year: 2018,
      mileage: 450000,
      nickname: 'Iron Horse',
      status: 'Needs Attention' as const,
      createdAt: new Date('2022-11-05'),
      updatedAt: new Date('2024-07-30'),
    },
    {
      id: 'truck-5',
      vin: '1FUJGLDR89LM98765',
      licensePlate: 'FLT-005',
      make: 'Volvo',
      model: 'VNL 760',
      year: 2022,
      mileage: 89000,
      nickname: 'Nordic Star',
      status: 'In Service' as const,
      createdAt: new Date('2024-01-12'),
      updatedAt: new Date('2024-08-01'),
    },
  ],

  maintenanceEntries: [
    {
      id: 'maint-1',
      truckId: 'truck-1',
      type: 'Oil Change' as const,
      date: new Date('2024-07-15'),
      mileage: 340000,
      cost: 350,
      notes: 'Regular oil change with filter replacement',
      performedBy: 'Mike\'s Garage',
      createdAt: new Date('2024-07-15'),
    },
    {
      id: 'maint-2',
      truckId: 'truck-2',
      type: 'Brake Inspection' as const,
      date: new Date('2024-07-28'),
      mileage: 298000,
      cost: 850,
      notes: 'Front brake pads replaced, rotors resurfaced',
      performedBy: 'TruckPro Service',
      createdAt: new Date('2024-07-28'),
    },
    {
      id: 'maint-3',
      truckId: 'truck-3',
      type: 'Tire Replacement' as const,
      date: new Date('2024-06-20'),
      mileage: 150000,
      cost: 1200,
      notes: 'Replaced 4 rear tires due to wear',
      performedBy: 'Tire Center Plus',
      createdAt: new Date('2024-06-20'),
    },
    {
      id: 'maint-4',
      truckId: 'truck-4',
      type: 'Engine Service' as const,
      date: new Date('2024-05-10'),
      mileage: 445000,
      cost: 2500,
      notes: 'Major engine service - replaced timing belt, water pump, thermostat',
      performedBy: 'Heavy Duty Mechanics',
      createdAt: new Date('2024-05-10'),
    },
    {
      id: 'maint-5',
      truckId: 'truck-5',
      type: 'DOT Inspection' as const,
      date: new Date('2024-08-01'),
      mileage: 89000,
      cost: 150,
      notes: 'Annual DOT inspection - passed',
      performedBy: 'Certified Inspection Station',
      createdAt: new Date('2024-08-01'),
    },
  ],

  parts: [
    {
      id: 'part-1',
      name: 'Engine Oil Filter',
      partNumber: 'LF3000',
      category: 'Filters' as const,
      cost: 25,
      supplier: 'FleetGuard',
      inventoryLevel: 12,
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'part-2',
      name: 'Brake Pads - Front',
      partNumber: 'BP4567',
      category: 'Brakes' as const,
      cost: 180,
      supplier: 'Bendix',
      inventoryLevel: 6,
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'part-3',
      name: 'Drive Tire 11R22.5',
      partNumber: 'DT1122',
      category: 'Tires' as const,
      cost: 450,
      supplier: 'Bridgestone',
      inventoryLevel: 8,
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'part-4',
      name: 'Transmission Fluid',
      partNumber: 'TF3000',
      category: 'Fluids' as const,
      cost: 35,
      supplier: 'Shell',
      inventoryLevel: 20,
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'part-5',
      name: 'Air Filter',
      partNumber: 'AF2000',
      category: 'Filters' as const,
      cost: 65,
      supplier: 'Donaldson',
      inventoryLevel: 10,
      createdAt: new Date('2024-01-01'),
    },
  ],

  downtimeEvents: [
    {
      id: 'down-1',
      truckId: 'truck-2',
      startDate: new Date('2024-07-28T08:00:00'),
      endDate: new Date('2024-07-30T16:00:00'),
      cause: 'Unexpected Failure' as const,
      description: 'Brake system failure - emergency repair required',
      estimatedCost: 1200,
      isOngoing: false,
      createdAt: new Date('2024-07-28'),
    },
    {
      id: 'down-2',
      truckId: 'truck-4',
      startDate: new Date('2024-05-08T14:00:00'),
      endDate: new Date('2024-05-12T10:00:00'),
      cause: 'Scheduled Maintenance' as const,
      description: 'Major engine service scheduled maintenance',
      estimatedCost: 2500,
      isOngoing: false,
      createdAt: new Date('2024-05-08'),
    },
    {
      id: 'down-3',
      truckId: 'truck-1',
      startDate: new Date('2024-06-15T11:00:00'),
      endDate: new Date('2024-06-15T17:00:00'),
      cause: 'Inspection' as const,
      description: 'DOT inspection and minor repairs',
      estimatedCost: 300,
      isOngoing: false,
      createdAt: new Date('2024-06-15'),
    },
  ],
};
